---

- name: Prep for k3s install
  hosts: nodes
  become: true
  become_user: root
  tasks:
    - name: Set ipv4 tables
      community.general.alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy

    - name: Set ipv6 tables
      community.general.alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy 

    - name: Reboot devices
      reboot:
