---

- name: Install K3s on Pis
  hosts: node2
  become: true
  become_user: root
  tasks:
    # - name: Flush iptables
    #   ansible.builtin.iptables:
    #     flush: yes
    - name: Set ipv4 tables
      community.general.alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy
    - name: Set ipv6 tables
      community.general.alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy 
    - name: Reboot devices
      reboot:
    - name: Install k3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -



# sudo iptables -F 
# sudo update-alternatives --set iptables /usr/sbin/iptables-legacy 
# sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy 
# sudo reboot